version: "3.8"

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8010
    volumes:
      - .:/code
    environment: 
      - "DJANGO_SECRET_KEY=${DJ_SECRET_KEY}"
    ports:
      - 8010:8010
    depends_on:
      - db

  db:
    image: postgres:11
    expose:
      - "5431"    
    ports:
      - 5431:5431
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    command: -p 5431

volumes:
  postgres_data:
